---
# Source: sysdig/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-sysdig
  labels:
    app: release-sysdig
    release: "release"
data:
  dragent.yaml: |
    new_k8s: true
    prometheus:
      enabled: true
      histograms: true
      interval: 10
      log_errors: true
      max_metrics: 1000
      max_metrics_per_process: 100
      max_tags_per_metric: 20
      process_filter:
      - exclude:
          process.name: docker-proxy
      - exclude:
          container.image: sysdig/agent
      - exclude:
          appcheck.match: prometheus
      - include:
          conf:
            path: '{container.label.io.prometheus.path}'
            port: '{container.label.io.prometheus.port}'
            port_filter:
            - exclude:
              - 9092
              - 9200
              - 9300
            - include: 9090-9500
            - include:
              - 9913
              - 9984
              - 24231
              - 42004
          container.label.io.prometheus.scrape: "true"
      - exclude:
          container.label.io.prometheus.scrape: "false"
      - include:
          conf:
            path: '{kubernetes.pod.annotation.prometheus.io/path}'
            port: '{kubernetes.pod.annotation.prometheus.io/port}'
          kubernetes.pod.annotation.prometheus.io/scrape: true
      - exclude:
          kubernetes.pod.annotation.prometheus.io/scrape: false
---
# Source: sysdig/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-sysdig
  labels:
    app: release-sysdig
    release: "release"
