---
# Source: sysdig/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-sysdig
  labels:
    app: release-sysdig
    release: "release"
type: Opaque
data:
 access-key : "ZDFhOTdmNzEtYjM1OS00ZDkzLWExMjUtOGM3ZDY5MjViY2U2"
